/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/model/fox1.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/fox1.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig" position={[-0.001, 0.126, 0.053]} rotation={[-0.048, 0.008, -0.001]}>
          <primitive object={nodes.spine} />
          <primitive object={nodes.IK} />
          <primitive object={nodes.neutral_bone} />
          <group name="Cube002">
            <skinnedMesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials.Base} skeleton={nodes.Cube002_1.skeleton} />
            <skinnedMesh name="Cube002_2" geometry={nodes.Cube002_2.geometry} material={materials['Material.001']} skeleton={nodes.Cube002_2.skeleton} />
            <skinnedMesh name="Cube002_3" geometry={nodes.Cube002_3.geometry} material={materials['Material.003']} skeleton={nodes.Cube002_3.skeleton} />
            <skinnedMesh name="Cube002_4" geometry={nodes.Cube002_4.geometry} material={materials['Material.002']} skeleton={nodes.Cube002_4.skeleton} />
            <skinnedMesh name="Cube002_5" geometry={nodes.Cube002_5.geometry} material={materials.Mouth} skeleton={nodes.Cube002_5.skeleton} />
            <skinnedMesh name="Cube002_6" geometry={nodes.Cube002_6.geometry} material={materials['Material.004']} skeleton={nodes.Cube002_6.skeleton} />
            <skinnedMesh name="Cube002_7" geometry={nodes.Cube002_7.geometry} material={materials['Material.005']} skeleton={nodes.Cube002_7.skeleton} />
            <skinnedMesh name="Cube002_8" geometry={nodes.Cube002_8.geometry} material={materials['Material.006']} skeleton={nodes.Cube002_8.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/fox1.gltf')
